<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryRepository extends EntityRepository
{

	public function findPaginated($page)
	{
		// DQL
		/*
		$em = $this->getEntityManager();

		$dql = "SELECT s, a
				FROM AppBundle\Entity\Story s 
				LEFT JOIN s.author a 
				WHERE s.isPublished = 1";
		$query = $em->createQuery($dql);
		*/

		//Doctrine Query Builder
		$qb = $this->createQueryBuilder("s");

		$qb->select('s')
			->addSelect('a')
			->leftJoin('s.author', 'a')
			->where('s.isPublished = 1');

		//commun aux deux
		$query = $qb->getQuery();

		$numPerPage = 10;
		$query->setMaxResults($numPerPage);
		$query->setFirstResult( ($page-1) * $numPerPage );
		$result = $query->getResult();

		return $result;
	}

}
